# Generated by Django 4.2.16 on 2024-12-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile/avatar.jpg",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
