# Generated by Django 4.2.16 on 2024-12-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='percent',
            field=models.FloatField(default=1),
        ),
    ]
