# Generated by Django 4.2.16 on 2024-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='percent',
            field=models.FloatField(default=0.01),
        ),
    ]
