# Generated by Django 4.2.16 on 2024-12-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_cart_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="is_ordered",
            field=models.BooleanField(default=False),
        ),
    ]
