# Generated by Django 4.2.16 on 2024-11-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(help_text='Maxsulot rangi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Maxsulot rasmi', null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(help_text="Maxsulotni o'lchami", max_length=255, null=True),
        ),
    ]
