# Generated by Django 4.2.16 on 2024-11-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_productimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': 'Maxsulot rasmi', 'verbose_name_plural': 'Maxsulot rasmlari'},
        ),
    ]
