# Generated by Django 4.2.16 on 2024-11-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
    ]
