# Generated by Django 4.2.16 on 2024-11-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_color_created_at_color_is_active_color_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Maxsulot rangi', 'verbose_name_plural': 'Maxsulot ranglari'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': "Maxsulot o'lchami", 'verbose_name_plural': "Maxsulot o'lchamlari"},
        ),
    ]
